appman updated

diff --git a/scripts/appman b/scripts/appman
--- a/scripts/appman
+++ b/scripts/appman
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="9.9.4"
+AMVERSION="9.9.5-8"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM/main"
@@ -93,11 +93,13 @@ RED='\033[0;31m'
 Gold='\033[0;33m'
 Green='\033[0;32m'
 LightBlue='\033[1;34m'
-DIVIDING_LINE="-----------------------------------------------------------------------------"
+
+command -v tput >/dev/null 2>&1 && TERMINAL_WIDTH="$(("$(tput cols)"-"3"))" || TERMINAL_WIDTH="${COLUMNS:-80}"
+DIVIDING_LINE=$(printf '%*s' "$TERMINAL_WIDTH" '' | tr ' ' '-')
 
 # Fit texts to an acceptable width
 _fit() {
-	command -v tput >/dev/null 2>&1 && fold -sw "$(("$(tput cols)"-"3"))" | sed 's/^/ /g' || fold -sw 77 | sed 's/^/ /g'
+	command -v tput >/dev/null 2>&1 && fold -sw "$TERMINAL_WIDTH" | sed 's/^/ /g' || fold -sw 77 | sed 's/^/ /g'
 }
 
 # DEVELOPER MODE
@@ -845,6 +847,14 @@ _check_version() {
 			if echo "$archived_apps" | grep -q "^$arg$"; then
 				APPVERSION="$APPVERSION is ARCHIVED"
 			fi
+			APPVERSION=$(echo "$APPVERSION" | sed 's/  / /g; s/ $//g')
+			if [ -f "$argpath"/AM-VERIFIED ]; then
+				if grep -q "Checksum failure" "$argpath"/AM-VERIFIED; then
+					APPVERSION=$(echo "$APPVERSION✖" | awk '{gsub(/✖/, "\033[31m✖\033[0m"); print}')
+				else
+					APPVERSION=$(echo "$APPVERSION✓" | awk '{gsub(/✓/, "\033[32m✓\033[0m"); print}')
+				fi
+			fi
 			if echo "$obsolete_apps" | grep -q "^$arg [0-9]"; then
 				obsolete_last_release=$(echo "$obsolete_apps" | grep "^$arg " | awk '{print $2}')
 				APPVERSION="$APPVERSION, of $obsolete_last_release"
@@ -1402,6 +1412,79 @@ _use_sync() {
 	echo "$DIVIDING_LINE"
 }
 
+_use_verify() {
+	# Check if checksum calc tools exist
+	if command -v sha1sum &>/dev/null && command -v sha256sum &>/dev/null && command -v sha512sum &>/dev/null && command -v md5sum &>/dev/null; then
+		[ -f "$argpath/AM-VERIFIED" ] && rm -f "$argpath"/AM-VERIFIED # Remove verified status
+		# Check if the download was a tarball/zip file
+		if { [ -f "$argpath/version" ] && grep -q '\.xz$\|\.zip$\|\.gz$' "$argpath/version"; } \
+		|| { [ -f "$argpath/AM-updater" ] && grep -q 'wget.*\.xz \|wget.*\.zip \|wget.*\.gz ' "$argpath/AM-updater"; } \
+		|| { [ ! -f "$argpath/version" ] && [ ! -f "$argpath/AM-updater" ] && [ -f "$argpath/updater.ini" ]; }; then
+			checksum_msg=$(echo $"Checksum auto-verified.")
+			printf "%b✔\033[0m %b \n" "${Green}" "$checksum_msg" | _fit
+			printf "Source is tarball/zip" > "$argpath"/AM-VERIFIED
+			return 1
+		# Search for hash files
+		elif [ -f "$argpath"/version ] && grep -qi "^http" "$argpath"/version; then
+			download_url=$(sort "$argpath"/version)
+		elif [ -f "$argpath"/AM-updater ] && grep -q "wget .*am-extras" "$argpath"/AM-updater; then
+			download_url=$(eval "$(grep "wget .*am-extras" "$argpath"/AM-updater | tr '()' '\n' | grep curl | head -1)" | xargs 2>/dev/null)
+		fi
+		if [ -n "$download_url" ]; then
+			# Search for zsync file
+			digest=$(curl -Ls "$download_url.zsync" | grep -a "SHA\|MD5")
+			if [ -z "$digest" ]; then
+				# Search other sources if no zsync file
+				for ext in digest DIGEST sha512 sha256 sha1 md5; do
+					digest=$(curl -Ls "$download_url.$ext")
+					# Skip empty responses (some CDNs return HTTP 404 with empty body)
+					[ -z "$digest" ] && continue
+					if ! echo "$digest" | grep -qi "not found\|access denied"; then
+						break
+					fi
+				done
+				if [ -z "$digest" ] || echo "$digest" | grep -qi "not found\|access denied"; then
+					return 1
+				fi
+			fi
+		else
+			checksum_msg=$(echo $"Checksum cannot be verified, missing download URL.")
+			printf "%b⚠️\033[0m %b \n" "${Gold}" "$checksum_msg" | _fit
+			return 1
+		fi
+		# Calculate checksums
+		if [ -f "$argpath"/"$arg" ]; then
+			checksum_sha1=$(sha1sum "$argpath/$arg" | awk '{print $1}')
+			checksum_sha256=$(sha256sum "$argpath/$arg" | awk '{print $1}')
+			checksum_sha512=$(sha512sum "$argpath/$arg" | awk '{print $1}')
+			checksum_md5=$(md5sum "$argpath/$arg" | awk '{print $1}')
+		elif [ -f "$argpath"/"$pure_arg" ]; then
+			checksum_sha1=$(sha1sum "$argpath/$pure_arg" | awk '{print $1}')
+			checksum_sha256=$(sha256sum "$argpath/$pure_arg" | awk '{print $1}')
+			checksum_sha512=$(sha512sum "$argpath/$pure_arg" | awk '{print $1}')
+			checksum_md5=$(md5sum "$argpath/$pure_arg" | awk '{print $1}')
+		else
+			checksum_msg=$(echo $"Checksum cannot be verified, mismatch in binary name.")
+			printf "%b✖\033[0m %b \n" "${RED}" "$checksum_msg" | _fit
+			return 1
+		fi
+		# Grep for any matching checksum
+		results=$(echo "$digest" | grep -a "$checksum_md5\|$checksum_sha1\|$checksum_sha256\|$checksum_sha512")
+		if [ -z "$results" ]; then
+			checksum_msg=$(echo $"Checksum does not match, please manually verify file integrity.")
+			printf "%b✖\033[0m %b \n" "${RED}" "$checksum_msg" | _fit
+			printf "Checksum failure" > "$argpath"/AM-VERIFIED
+		else
+			checksum_msg=$(echo $"Checksum verified.")
+			printf "%b✔\033[0m %b \n" "${Green}" "$checksum_msg" | _fit
+			printf "MD5: %b\nSHA1: %b\nSHA256: %b\nSHA512: %b" "$checksum_sha1" "$checksum_sha256" "$checksum_sha512" "$checksum_md5" > "$argpath"/AM-VERIFIED
+		fi
+	else
+		echo $"Checksum calculation tools do not exist, please install coreutils." | sed 's/coreutils/"coreutils"/g'
+	fi
+	unset checksum_sha1 checksum_sha256 checksum_sha512 checksum_md5 digest download_url results
+}
+
 ################################################################################################################################################################
 #				UPDATE
 ################################################################################################################################################################
@@ -1469,15 +1552,24 @@ _update_run_updater() {
 			sed -i "s#https://api.github.com#$ALT_GH#g" "$argpath"/AM-updater
 		fi
 	fi
+	if grep -sq "Checksum failure" "$argpath"/AM-VERIFIED; then
+		rm -f "$argpath"/version # Triggers AM-updater to re-download the Appimage binary
+	fi
 	if [ -z "$debug_update" ]; then
 		"$argpath"/AM-updater >/dev/null 2>&1
 	else
 		"$argpath"/AM-updater
 	fi
 	sed -i "s#$ALT_GH#https://api.github.com#g" "$argpath"/AM-updater 2>/dev/null
+	checksum_msg=$(_use_verify | xargs 2>/dev/null)
 	end=$(date +%s)
 	timelapsed=$((end - start))
-	[ "$timelapsed" = 1 ] && printf $" %b✔\033[0m $APPNAME is updated, $timelapsed second elapsed! \n" "${Green}" || printf $" %b✔\033[0m $APPNAME is updated, $timelapsed seconds elapsed! \n" "${Green}"
+	if [ "$timelapsed" = 1 ]; then
+		timelapsed_msg=$(printf $" %b✔\033[0m $APPNAME is updated, $timelapsed second elapsed! \n" "${Green}")
+	else
+		timelapsed_msg=$(printf $" %b✔\033[0m $APPNAME is updated, $timelapsed seconds elapsed! \n" "${Green}")
+	fi
+	printf -- "%b%b\n" "$timelapsed_msg" "$checksum_msg" | sed 's/^ //g; s/^/ /g'
 	[ -n "$debug_update" ] && echo "$DIVIDING_LINE"
 }
 
@@ -1583,6 +1675,7 @@ _use_update() {
 			else
 				UPDATERS=$(cd "$argpath" 2>/dev/null && find . -name "*update*" -print 2>/dev/null)
 				[ -n "$UPDATERS" ] && arg_autoupdatable=", it may have its update system"
+				[ "$arg" = "$AMCLI" ] && arg_autoupdatable=", use \"-s\" instead"
 				printf $" %b✖\033[0m %b cannot be updated%b\n" "${RED}" "$(echo "$arg" | tr '[:lower:]' '[:upper:]')" "$arg_autoupdatable"
 			fi
 		done
@@ -1621,17 +1714,15 @@ _use_force_latest() {
 # HANDLE ALL THE EXTERNAL MODULES
 _use_module() {
 	# Test if module exists
+	if [ ! -f "$MODULES_PATH/$MODULE" ] && [ -f "$APPMANCONFIG/appman-mode" ] && { [ "$CLI" = am ] || [ "$CLI" = APP-MANAGER ]; }; then
+		[ -f "/usr/lib/am/modules/$MODULE" ] && MODULES_PATH="/usr/lib/am/modules"
+		[ -f "$(readlink -f /opt)/am/modules/$MODULE" ] && MODULES_PATH="$(readlink -f /opt)/am/modules"
+	fi
 	if [ ! -f "$MODULES_PATH/$MODULE" ]; then
-		if [ "$CLI" = am ] && [ -f "$APPMANCONFIG"/appman-mode ] && [ -f "/usr/lib/am/modules/$MODULE" ]; then
-			MODULES_PATH="/usr/lib/am/modules"
-		elif [ "$CLI" = am ] && [ -f "$APPMANCONFIG"/appman-mode ] && [ -f "$(readlink -f /opt)/am/modules/$MODULE" ]; then
-			MODULES_PATH="$(readlink -f /opt)/am/modules"
-		else
-			_online_check
-			if ! wget -q "$MODULES_SOURCE/$MODULE" -O "$MODULES_PATH/$MODULE"; then
-				echo $" Module not found, run \"$AMCLI -s\" to update \"$AMCLIUPPER\""
-				exit 1
-			fi
+		_online_check
+		if ! wget -q "$MODULES_SOURCE/$MODULE" -O "$MODULES_PATH/$MODULE"; then
+			echo $" Module not found, run \"$AMCLI -s\" to update \"$AMCLIUPPER\""
+			exit 1
 		fi
 	fi
 	# Source module
