updated appman

diff --git a/scripts/appman b/scripts/appman
--- a/scripts/appman
+++ b/scripts/appman
@@ -2,6 +2,7 @@
 
 DIR="$( cd "$( dirname "$0" )" && pwd )"
 CLI=$(basename "$0")
+AMVERSION="6.6.2-1"
 
 SCRIPTDIR="$(if command -v xdg-user-dir &>/dev/null; then xdg-user-dir DESKTOP; else echo $HOME; fi)"
 
@@ -13,9 +14,9 @@ else
 fi
 
 if [ -n "$XDG_DATA_HOME" ]; then
-        DATADIR="$XDG_DATA_HOME"
+	DATADIR="$XDG_DATA_HOME"
 else
-        DATADIR="$HOME/.local/share"
+	DATADIR="$HOME/.local/share"
 fi
 
 function _am(){
@@ -30,49 +31,48 @@ function _am(){
 	mkdir -p "$AMPATH"/modules
 }
 
+# Helper functions don't need to be defined inside the parent function
+function prompt_for_directory() {
+	local location
+	read -r -ep "Please, write the name or the path of your custom application's folder: $(echo -e '\n\n '$HOME'/')" location
+	echo "$location"
+}
+
+function validate_directory() {
+	local location=$1
+	if [[ "$location" == "" ]]; then
+		echo -e "--------------------------------------------------------------------------"
+		echo "OPERATION ABORTED!"
+		exit  1
+	elif [[ "$location" == ".local/bin" ]]; then
+		echo -e "--------------------------------------------------------------------------\n"
+		echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
+		echo -e "--------------------------------------------------------------------------\n"
+		exit  1
+		else
+		local location_appman="${location/#$HOME}"
+		location_appman="${location_appman// /-}"
+		location_appman="${location_appman#/}"
+		location_appman="${location_appman%/}"
+		echo "$location_appman"
+	fi
+}
+
+function initialize_appman() {
+	APPSDIR=$1
+	mkdir -p ~/"$APPSDIR"/appman/.cache
+	mkdir -p ~/"$APPSDIR"/appman/modules
+	mkdir -p ~/.local/bin "$DATADIR"/applications "$DATADIR"/icons
+	AMCLI="appman"
+	AMCLIPATH="$DIR/$AMCLI"
+	SUDOCOMMAND=""
+	COMPLETIONPATH="$HOME"
+	COMPLETIONFILE=".bash_completion"
+	APPSPATH="$HOME/$APPSDIR"
+	AMPATH="$HOME/$APPSDIR/$AMCLI"
+}
+
 function _appman() {
-	# Helper functions defined inside the parent function
-	function prompt_for_directory() {
-		local location
-		read -r -ep "Please, write the name or the path of your custom application's folder: $(echo -e '\n\n '$HOME'/')" location
-		echo "$location"
-	}
-
-	function validate_directory() {
-		local location=$1
-		if [[ "$location" == "" ]]; then
-			echo -e "--------------------------------------------------------------------------"
-			echo "OPERATION ABORTED!"
-			exit  1
-		elif [[ "$location" == ".local/bin" ]]; then
-			echo -e "--------------------------------------------------------------------------\n"
-			echo -e " 💀 ERROR, you can't install applications into a '$PATH'\n\n The directory ~/.local/bin and 'bin' folders are used for executables.\n\n Please, choose a different path and retry! \n"
-			echo -e "--------------------------------------------------------------------------\n"
-			exit  1
-			else
-			local location_appman="${location/#$HOME}"
-			location_appman="${location_appman// /-}"
-			location_appman="${location_appman#/}"
-			location_appman="${location_appman%/}"
-			echo "$location_appman"
-		fi
-	}
-
-	function initialize_appman() {
-		APPSDIR=$1
-		mkdir -p ~/"$APPSDIR"/appman/.cache
-		mkdir -p ~/"$APPSDIR"/appman/modules
-		mkdir -p ~/.local/bin "$DATADIR"/applications "$DATADIR"/icons
-		AMCLI="appman"
-		AMCLIPATH="$DIR/$AMCLI"
-		SUDOCOMMAND=""
-		COMPLETIONPATH="$HOME"
-		COMPLETIONFILE=".bash_completion"
-		APPSPATH="$HOME/$APPSDIR"
-		AMPATH="$HOME/$APPSDIR/$AMCLI"
-	}
-
-	# Main execution
 	if [[ ! -f "$APPMANCONFIG"/appman-config ]]; then
 		echo "--------------------------------------------------------------------------"
 		echo " >>> Thank you for choosing AppMan!"
@@ -86,7 +86,6 @@ function _appman() {
 		echo 'decide to change your choice in the future, first remove all the programs'
 		echo 'and then edit the ~/.config/appman/appman-config text file.'
 		echo -e "--------------------------------------------------------------------------\n"
-
 		local location=$(prompt_for_directory)
 		local validated_location=$(validate_directory "$location")
 		mkdir -p "$APPMANCONFIG"
@@ -120,6 +119,20 @@ export AMCATALOGUEICONS="https://raw.githubusercontent.com/Portable-Linux-Apps/P
 # Determine system architecture and current user
 export arch="$HOSTTYPE"
 export currentuser="$USER"
+if [ "$AMCLI" == am ]; then
+	ampathowner=$(ls -ld /opt/am | awk 'NR==1 {print $3}')
+	if [ "$ampathowner" != "$currentuser" ]; then
+		echo ' 💀 ERROR: you are not the owner of /opt/am, so you cannot use "AM"'
+		echo '--------------------------------------------------------------------------'
+		echo ' The user that have installed "AM" on this system is "'"$ampathowner"'"'
+		echo ' you are only allowed to use the installed apps, not to manage them.'
+		echo '--------------------------------------------------------------------------'
+		echo ' Please, contact "'"$ampathowner"'" to change the ownership of /opt/am or'
+		echo ' consider using "AppMan" instead, see https://github.com/ivan-hc/AppMan'
+		echo '--------------------------------------------------------------------------'
+		exit
+	fi
+fi
 
 if [[ -f "$AMPATH"/new-repo.txt ]]; then
 	AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
@@ -164,8 +177,8 @@ done
 
 # Exit if any essential command is missing
 if [ -n "$missing_deps" ]; then
-  printf "\nMissing essential commands: %s\nInstall the above and try again\n\n" "${missing_deps[*]}"
-  exit 1
+	printf "\nMissing essential commands: %s\nInstall the above and try again\n\n" "${missing_deps[*]}"
+	exit 1
 fi
 
 rm -rf "$AMPATH/options"
@@ -179,6 +192,7 @@ cat <<-HEREDOC >> "$AMPATH/options"
 	install
 	list
 	lock
+	neodb
 	newrepo
 	nolibfuse
 	overwrite
@@ -191,6 +205,7 @@ cat <<-HEREDOC >> "$AMPATH/options"
 	update
 	web
 	--apps
+	--byname
 	--convert
 	--debug
 	--disable-completion
@@ -200,16 +215,16 @@ cat <<-HEREDOC >> "$AMPATH/options"
 	--home
 	--launcher
 	--less
-	--libs
 	--rollback
 	--sandbox
+	--silent
 	--user
 HEREDOC
 
 function _no_sudo(){
-	if [ -n "$SUDO_COMMAND" ]; then 
-		printf "\n WARNING: You don't need to use SUDO for this.\n\n"; 
-		exit 1; 
+	if [ -n "$SUDO_COMMAND" ]; then
+		printf "\n WARNING: You don't need to use SUDO for this.\n\n";
+		exit 1;
 	fi
 }
 
@@ -242,168 +257,102 @@ function _patch_bashrc_and_profile(){
 # Set header authorization if GitHub API key file exists
 [ -f "$AMPATH/ghapikey.txt" ] && HeaderAuthWithGITPAT=" --header \"Authorization: token $(<"$AMPATH/ghapikey.txt")\" "
 
-case "$1" in
+# Check version of the installed apps
+function _check_version(){
+	rm -f $AMPATH/.cache/version-args
+	cd $APPSPATH &&
+	INSTALLED_APPS=$(find -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2> /dev/null | sort -rh | sed 's@.*	@@')
+	for arg in $INSTALLED_APPS; do
+		 if test -f ./$arg/remove 2>/dev/null; then
+	 		if test -f ./$arg/version 2>/dev/null; then
+				APPVERSION=$(cat $APPSPATH/$arg/version | head -1 | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
+				if [ -z "$APPVERSION" ]; then
+					if test -f ./$arg/*.zsync 2>/dev/null; then
+						APPVERSION=$(strings -d ./$arg/*.zsync | grep -i $arg | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
+					elif grep -q -- "-$arch/" ./$arg/version; then
+						ALPHANUMERICTEST=$(cat $APPSPATH/$arg/version | tr '-' '\n' | grep -vi "appimage\|$arg\|$arch" | tail -1)
+						if ! [[ "$ALPHANUMERICTEST" =~ [^a-zA-Z0-9] ]]; then
+							APPVERSION="$ALPHANUMERICTEST"
+						fi
+					elif ! sed "s/$arch//g" $APPSPATH/$arg/version | grep -q "[0-9]"; then
+						if grep -qi "/continuous/" $APPSPATH/$arg/version 2>/dev/null; then
+							APPVERSION="continuous"
+						fi
+					else
+						APPVERSION=$(cat $APPSPATH/$arg/version | sed 's:.*/::' | tr '-' '\n' | grep -vi "appimage\|$arg\|$arch" | grep "[0-9]" | head -1)
+					fi
+				fi
+			elif test -f ./$arg/updater 2>/dev/null; then
+				APPVERSION=$($APPSPATH/$arg/updater -d $APPSPATH/$arg/$arg 2>/dev/null | grep -i $arg | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
+				if [ -z "$APPVERSION" ]; then
+					APPVERSION=$(grep -i "version=" $APPSPATH/$arg/* 2>/dev/null | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
+				fi
+			elif [ "$arg" == "$AMCLI" ]; then
+				APPVERSION=$($AMCLIPATH -v)
+			elif grep -qi "version=" ./$arg/* 2>/dev/null; then
+				APPVERSION=$(grep -i "version=" $APPSPATH/$arg/* 2>/dev/null | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
+			elif echo "$arg" | grep -q "ffwa-"; then
+				APPVERSION="WebApp"
+			elif cat $APPSPATH/$arg/remove 2> /dev/null | grep -q "usr/local/lib"; then
+				APPVERSION=$(strings -d $(cat $APPSPATH/$arg/remove | tr ' ' '\n' | grep "usr/local/lib") | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | tail -1)
+			else
+				APPVERSION="unknown"
+			fi
+			if [ -z "$APPVERSION" ]; then
+				APPVERSION="unknown"
+			fi
+			echo " ◆ $arg	|	$APPVERSION" >> $AMPATH/.cache/version-args
+		fi
+	done
+}
 
-  '')	echo -e "\n USAGE: '$AMCLI [option]'\n        '$AMCLI [option] [argument]'\n\n Run the '$AMCLI -h' command to find out more\n";;
+# All the options
+function source_module() {
+	source "$AMPATH/modules/$MODULE" "$@"
+}
 
-  '-h'|'help')
+function get_module() {
+	wget -q "$AMREPO/modules/$MODULE" -O "$AMPATH/modules/$MODULE"
+	chmod a+x "$AMPATH/modules/$MODULE"
+}
 
-	if ! test -f "$AMPATH"/modules/help.am; then
-		wget -q "$AMREPO"/modules/help.am -O "$AMPATH"/modules/help.am
-		chmod a+x "$AMPATH"/modules/help.am
+function test_module() {
+	if ! test -f "$AMPATH/modules/$MODULE"; then
+		get_module
 	fi
+}
 
-	source "$AMPATH"/modules/help.am
-  	;;
+function use_module_sudo() {
+	test_module
+	source_module "$@"
+}
 
-  '-a'|'about'|'-l'|'list'|'-q'|'query')
-
+function use_module() {
 	_no_sudo
+	use_module_sudo "$@"
+}
 
-	[[ -f "$AMPATH"/modules/database.am ]] || {
-		wget -q "$AMREPO"/modules/database.am -O "$AMPATH"/modules/database.am
-		chmod a+x "$AMPATH"/modules/database.am
-	}
-
-	source "$AMPATH"/modules/database.am "$@"
-	;;
-
-  '-b'|'backup'|'-o'|'overvrite'|'lock'|'unlock')
-
-	_no_sudo
-
-	if ! test -f "$AMPATH"/modules/no-updates.am; then
-		wget -q "$AMREPO"/modules/no-updates.am -O "$AMPATH"/modules/no-updates.am
-		chmod a+x "$AMPATH"/modules/no-updates.am
-	fi
-
-	source "$AMPATH"/modules/no-updates.am "$@"
-	;;
-
-  '-c'|'clean')
-
-  	_no_sudo
-
-	if ! test -f "$AMPATH"/modules/clean.am; then
-		wget -q "$AMREPO"/modules/clean.am -O "$AMPATH"/modules/clean.am
-		chmod a+x "$AMPATH"/modules/clean.am
-	fi
-
-	source "$AMPATH"/modules/clean.am
-	;;
-
-  '-d'|'download')
-
-	_no_sudo
+function use_module_online_sudo () {
 	_online_check
+	use_module "$@"
+}
 
-	if ! test -f "$AMPATH"/modules/download.am; then
-		wget -q "$AMREPO"/modules/download.am -O "$AMPATH"/modules/download.am
-		chmod a+x "$AMPATH"/modules/download.am
-	fi
-
-	source "$AMPATH"/modules/download.am "$@"
-	;;
-
-  '-f'|'files')
-
-  	_no_sudo
-
-	if ! test -f "$AMPATH"/modules/files.am; then
-		wget -q "$AMREPO"/modules/files.am -O "$AMPATH"/modules/files.am
-		chmod a+x "$AMPATH"/modules/files.am
-	fi
-
-	source "$AMPATH"/modules/files.am
-	;;
-
-  '-H'|'--home'|'--firejail'|'--sandbox')
-
+function use_module_online () {
 	_no_sudo
+	use_module_online_sudo "$@"
+}
 
-	if ! test -f "$AMPATH"/modules/sandboxes.am; then
-		wget -q "$AMREPO"/modules/sandboxes.am -O "$AMPATH"/modules/sandboxes.am
-		chmod a+x "$AMPATH"/modules/sandboxes.am
-	fi
-
-	source "$AMPATH"/modules/sandboxes.am "$@"
-	;;
-
-  '-i'|'install')
-
-	_online_check
-
-	if ! test -f "$AMPATH"/modules/install.am; then
-		wget -q "$AMREPO"/modules/install.am -O "$AMPATH"/modules/install.am
-		chmod a+x "$AMPATH"/modules/install.am
-	fi
-
-	source "$AMPATH"/modules/install.am "$@"
-	;;
-
-  '-R'|'-r'|'remove')
-
-	if ! test -f "$AMPATH"/modules/remove.am; then
-		wget -q "$AMREPO"/modules/remove.am -O "$AMPATH"/modules/remove.am
-		chmod a+x "$AMPATH"/modules/remove.am
-	fi
-
-	source "$AMPATH"/modules/remove.am "$@"
-	;;
-
-  '-s'|'sync')
-
-	_no_sudo
-	_online_check
-
-	if ! test -f "$AMPATH"/modules/sync.am; then
-		wget -q "$AMREPO"/modules/sync.am -O "$AMPATH"/modules/sync.am
-		chmod a+x "$AMPATH"/modules/sync.am
-	fi
-
-	source "$AMPATH"/modules/sync.am "$@"
-	;;
-
-  '-t'|'template')
-
-	_no_sudo
-	_online_check
-
-	if ! test -f "$AMPATH"/modules/template.am; then
-		wget -q "$AMREPO"/modules/template.am -O "$AMPATH"/modules/template.am
-		chmod a+x "$AMPATH"/modules/template.am
-	fi
-
-	source "$AMPATH"/modules/template.am "$@"
-	;;
-
-  '-u'|'-U'|'update'|'--force-latest') 
-
-	_no_sudo
-	_online_check
-
-	if ! test -f "$AMPATH"/modules/update.am; then
-		wget -q "$AMREPO"/modules/update.am -O "$AMPATH"/modules/update.am
-		chmod a+x "$AMPATH"/modules/update.am
-	fi
-
-	source "$AMPATH"/modules/update.am "$@"
-	;;
-
-  '--disable-completion')
-
-  	
-  	if [ "$(grep -o "$AMCLI" 0<"$COMPLETIONPATH/$COMPLETIONFILE" | head -1)" == "$AMCLI" ]; then
-  		grep -v 'complete -W "$(cat '"$AMPATH"'/list 2>/dev/null)" '"$AMCLI"'' "$COMPLETIONPATH/$COMPLETIONFILE" > "$AMPATH"/$COMPLETIONFILE.backup &&
+function use_disable-completion() {
+	if [ "$(grep -o "$AMCLI" 0<"$COMPLETIONPATH/$COMPLETIONFILE" | head -1)" == "$AMCLI" ]; then
+		grep -v 'complete -W "$(cat '"$AMPATH"'/list 2>/dev/null)" '"$AMCLI"'' "$COMPLETIONPATH/$COMPLETIONFILE" > "$AMPATH"/$COMPLETIONFILE.backup &&
 		$SUDOCOMMAND mv "$AMPATH"/$COMPLETIONFILE.backup "$COMPLETIONPATH/$COMPLETIONFILE"
 		echo " Completion disabled! "
 	else
 		echo " Completion script is NOT enabled! "
 	fi
-	;;
+}
 
-  '--enable-completion')
-
+function use_enable_completion() {
 	if [ "$(grep -o "$AMCLI" 0<"$COMPLETIONPATH/$COMPLETIONFILE" | head -1)" == "$AMCLI" ]; then
 		echo " Completion script is already enabled!"
 	else
@@ -420,43 +369,30 @@ case "$1" in
 		$SUDOCOMMAND mv "$COMPLETIONFILE" "$COMPLETIONPATH/" 2> /dev/null
 		echo " Completion has been enabled!"
 	fi
-	;;
-
-  '--launcher')
-
-	_no_sudo
-
-	if ! test -f "$AMPATH"/modules/launcher.am; then
-		wget -q "$AMREPO"/modules/launcher.am -O "$AMPATH"/modules/launcher.am
-		chmod a+x "$AMPATH"/modules/launcher.am
+	if [ -f "$HOME/.zshrc" ] || [ -f "$ZDOTDIR/.zshrc" ]; then
+		if [ -n "$ZDOTDIR" ]; then
+			ZSHDIR="$ZDOTDIR"
+		else
+			ZSHDIR="$HOME"
+		fi
+		if grep -q "source $ZSHDIR/$COMPLETIONFILE" "$ZSHDIR/.zshrc"; then
+			echo "Zsh completion already enabled!"
+		else
+			echo '#!/usr/bin/env bash' >> "$ZSHDIR/$COMPLETIONFILE"
+			echo 'complete -W "$(cat '"$AMPATH"'/list 2>/dev/null)" '"$AMCLI"'' >> "$ZSHDIR/$COMPLETIONFILE"
+			chmod a+x "$ZSHDIR/$COMPLETIONFILE"
+			echo -e "\nautoload bashcompinit\nbashcompinit\nsource $ZSHDIR/$COMPLETIONFILE" >> "$ZSHDIR/.zshrc"
+		fi
 	fi
+}
 
-	source "$AMPATH"/modules/launcher.am "$@"
-	;;
-
-  '--rollback')
-
+function use_appman() {
 	_no_sudo
 	_online_check
-
-	if ! test -f "$AMPATH"/modules/rollback.am; then
-		wget -q "$AMREPO"/modules/rollback.am -O "$AMPATH"/modules/rollback.am
-		chmod a+x "$AMPATH"/modules/rollback.am
-	fi
-
-	source "$AMPATH"/modules/rollback.am "$@"
-	;;
-
-  '--user'|'appman')
-
-  	_no_sudo
-  	_online_check
-
 	if [ "$AMCLI" == appman ] 2>/dev/null; then
 		echo " This function only works for AM"
 		exit
 	fi
-
 	RED='\033[0;31m'; LightBlue='\033[1;34m'
 	if test -f /opt/am/appman; then
 		_appman
@@ -465,39 +401,92 @@ case "$1" in
 		_appman
 		wget -q "$AMREPO"/APP-MANAGER -O /opt/am/appman && chmod a+x /opt/am/appman
 		echo -e "Please run '${RED}alias am=/opt/am/appman\033[0m' to made 'AM' act exactly like 'AppMan' for\nthe current session or save this command to your '"'~/.bashrc'"' file to make the\nchanges permanent."
-  	fi
-  	;;
-
-  'apikey'|'newrepo')
-
-	_no_sudo
-	_online_check
-
-	if ! test -f "$AMPATH"/modules/devtools.am; then
-		wget -q "$AMREPO"/modules/devtools.am -O "$AMPATH"/modules/devtools.am
-		chmod a+x "$AMPATH"/modules/devtools.am
 	fi
+}
 
-	source "$AMPATH"/modules/devtools.am "$@"
-	;;
-
-  'nolibfuse')
-
-	_no_sudo
-	_online_check
-
-	if ! test -f "$AMPATH"/modules/nolibfuse.am; then
-		wget -q "$AMREPO"/modules/nolibfuse.am -O "$AMPATH"/modules/nolibfuse.am
-		chmod a+x "$AMPATH"/modules/nolibfuse.am
-	fi
-
-	source "$AMPATH"/modules/nolibfuse.am "$@"
-	;;
-
-  'version'|'-v'|'--version')
-
-  	echo "6.4";;
-
-  *) exec "$AMCLIPATH" ;;
-
+case "$1" in
+	'')
+		echo -e "\n USAGE: '$AMCLI [option]'\n        '$AMCLI [option] [argument]'\n\n Run the '$AMCLI -h' command to find out more\n"
+		;;
+	'-a'|'about'|'-l'|'list'|'-q'|'query')
+		MODULE="database.am"
+		use_module "$@"
+		;;
+	'-b'|'backup'|'-o'|'overwrite'|'lock'|'unlock')
+		MODULE="no-updates.am"
+		use_module "$@"
+		;;
+	'-c'|'clean')
+		MODULE="clean.am"
+		use_module
+		;;
+	'-d'|'download')
+		MODULE="download.am"
+		use_module_online "$@"
+		;;
+	'-f'|'files')
+		MODULE="files.am"
+		use_module "$@"
+		;;
+	'-h'|'help')
+		MODULE="help.am"
+		use_module "$@"
+		;;
+	'-H'|'--home'|'--firejail'|'--sandbox')
+		MODULE="sandboxes.am"
+		use_module "$@"
+		;;
+	'-i'|'install')
+		MODULE="install.am"
+		use_module_online_sudo "$@"
+		;;
+	'-R'|'-r'|'remove')
+		MODULE="remove.am"
+		use_module_sudo "$@"
+		;;
+	'-s'|'sync')
+		MODULE="sync.am"
+		use_module_online "$@"
+		;;
+	'-t'|'template')
+		MODULE="template.am"
+		use_module_online "$@"
+		;;
+	'-u'|'-U'|'update'|'--force-latest')
+		MODULE="update.am"
+		use_module_online "$@"
+		;;
+	'--disable-completion')
+		use_disable-completion
+		;;
+	'--enable-completion')
+		use_enable_completion
+		;;
+	'--launcher')
+		MODULE="launcher.am"
+		use_module "$@"
+		;;
+	'--rollback')
+		MODULE="rollback.am"
+		use_module_online "$@"
+		;;
+	'--user'|'appman')
+		use_appman
+		;;
+	'neodb'|'apikey'|'newrepo')
+		MODULE="devtools.am"
+		use_module_online "$@"
+		;;
+	'nolibfuse')
+		MODULE="nolibfuse.am"
+		use_module_online "$@"
+		;;
+	'version'|'-v'|'--version')
+		echo "$AMVERSION"
+		;;
+	*)
+		exec "$AMCLIPATH"
+		;;
 esac
+
+# vim:tabstop=4:shiftwidth=4:expandtab
