added new scripts, updated old ones

diff --git a/scripts/doi2bib b/scripts/doi2bib
--- a/scripts/doi2bib
+++ b/scripts/doi2bib
@@ -18,12 +18,53 @@
 # Original script by Conner McDaniel
 # https://github.com/connermcd/bin
 
+display_help() {
+    echo "Usage: doi2bib <DOI> [options]"
+    echo
+    echo "Fetches the BibTeX format for a given DOI from the CrossRef API."
+    echo
+    echo "Arguments:"
+    echo "  <DOI>        The DOI (Digital Object Identifier) for the publication."
+    echo
+    echo "Options:"
+    echo "  -h, --help   Display this help message."
+    echo "  -f, --format Format the bib output."
+}
+
+if [[ "$1" == "--help" || "$1" == "-h" ]]; then
+    display_help
+    exit 0
+fi
+
+# Check if DOI is provided
+if [ -z "$1" ]; then
+    echo "Error: DOI is required."
+    display_help
+    exit 1
+fi
+
+format=false
+
+if [[ "$2" == "--format" || "$2" == "-f" ]]; then
+    format=true
+fi
+
 set -e
 
 result=
-i=
-while [[ $i < 10 && "$result" != *"author = "* ]]; do
-    result=$(curl -s "http://api.crossref.org/works/$1/transform/application/x-bibtex")
+i=0
+while [[ $i < 10 && "$result" != *"@"* ]]; do
+    result=$(curl -s -L -H "Accept: application/x-bibtex" "https://api.crossref.org/works/$1/transform")
+    # result=$(curl -s "http://api.crossref.org/works/$1/transform/application/x-bibtex")
     i=$(( $i + 1 ))
 done
-echo "$result"
+
+
+if $format; then
+    resource_file=$(mktemp)
+    bib=$(echo "$result" | bibtool -r "$resource_file")
+    rm "$resource_file"
+    echo "$bib"
+else
+    echo "$result"
+fi
diff --git a/scripts/pdf2doi b/scripts/pdf2doi
--- a/scripts/pdf2doi
+++ b/scripts/pdf2doi
@@ -15,6 +15,28 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
+display_help() {
+    echo "Usage: pdf2doi <PDF file>"
+    echo
+    echo "Extracts the first DOI (Digital Object Identifier) from the References section of a PDF file."
+    echo
+    echo "Options:"
+    echo "  -h, --help    Display this help message and exit."
+    echo
+}
+
+if [[ "$1" == "--help" || "$1" == "-h" ]]; then
+    display_help
+    exit 0
+fi
+
+# [x]TODO: check for input <13-01-26, pallav> #
+if [[ -z "$1" ]]; then
+    echo "Error: No PDF file provided."
+    display_help
+    exit 1
+fi
+
 
 set -e
 
